@startmindmap
* **VitaStore**\nИерархическая карта бизнес-возможностей\nуровня L1 и L2 (Heatmap)
** 1. Управление магазином
***[#red] Кассовые операции
***[#red] Печать ценников
***[#yellow] Приёмка товара
***[#yellow] Инвентаризация
** 2. Клиентский опыт
***[#red] Поддержка клиентов (Tier 1)
***[#yellow] Поддержка клиентов (Tier 2)
***[#yellow] Управление возвратами
***[#lime] Программа лояльности
***[#lime] Промоакции и скидки\n(Promo Engine)
***[#lime] Самовывоз из магазина у дома\n(Click & Collect)
** 3. Управление поставками
***[#yellow] Транспортная логистика
***[#yellow] Управление поставщиками
***[#lime] Омниканальная логистика\n(Smart Fulfillment)
** 4. Финансы и учёт
***[#red] Инкассация
***[#yellow] Централизованный учёт\n(SAP ERP)
** 5. Инфраструктура и IT
***[#red] Инфраструктура магазина\n(сервера, сеть)
***[#red] Администрирование\n(обновления, бэкапы)
***[#yellow] Поддержка\n(Service Desk)
***[#yellow] Безопасность (инфраструктурная)\n(WAF, DDoS)
***[#lime] Безопасность\n(политики, аудит, прочее)
** 6. Интеграция данных
***[#red] Маппинг номенклатуры\n(SKU Matching)
***[#yellow] Управление мастер-данными\n(MDM)
***[#lime] BI-витрины и аналитика
** 7. Работа с вендорами
***[#red] Управление оборудованием/терминалами
***[#yellow] Контракты с платежными системами
** 8. Маркетинг
***[#red] Управление рекламой
***[#yellow] Маркетинговые кампании
** 9. Управление персоналом (HR)
***[#yellow] Управление персоналом\n(смены, премии)
***[#yellow] Найм и адаптация
@endmindmap
